package cl.gob.scj.sgdp.tipos;

public enum ModuloType {

	EJECUCION_DE_TAREA ("EJECUCION DE TAREA", 1),
	HISTORIAL_DE_DOCUMENTOS ("HISTORIAL DE DOCUMENTOS", 2),
	DETALLE_DE_DOCUMENTO("DETALLE DE DOCUMENTO", 3),
	DETALLE_DE_EXPEDIENTE_EN_DISTRIBUCION("DETALLE DE EXPEDIENTE EN DISTRIBUCION", 4),
	DOCUMENTO_EN_DISTRIBUCION("DOCUMENTO EN DISTRIBUCION", 5),
	DOCUMENTO_REQUERIDO_FORMUlARIO("DOCUMENTO REQUERIDO FORMULARIO", 6),
	DOCUMENTO_PARA_FIRMA_MASIVA("DOCUMENTO PARA FIRMA MASIVA", 7),
	NOTIFICACION_SEGUIMIENTO("NOTIFICACION SEGUIMIENTO", 8),
	RESULTADO_DE_BUSQUEDA("RESULTADO DE BUSQUEDA", 9),
	SOLICITUD_CREACION_EXPEDIENTE("SOLICITUD CREACION EXPEDIENTE", 10),
	DETALLE_DE_EXPEDIENTE("DETALLE DE EXPEDIENTE", 11),
	DISTRIBUCION_DE_DOCUMENTOS("DISTRIBUCION DE DOCUMENTOS", 12),
	ANULACION_DE_DOCUMENTO("ANULACION_DE_DOCUMENTO", 13),
	LISTA_DE_DISTRIBUCION("LISTA_DE_DISTRIBUCION", 14)
	;
	
	private final String nombreModulo;
	private final long idModulo;
	
	private ModuloType(String nombreModulo, long idModulo) {
		this.nombreModulo = nombreModulo;
		this.idModulo = idModulo;
	}

	public String getNombreModulo() {
		return nombreModulo;
	}

	public long getIdModulo() {
		return idModulo;
	}	
	
}
