package cl.gob.scj.sgdp.tipos;

public enum PermisoType {

	CREAR_EXPEDIENTE ("CREAR_EXPEDIENTE"),
	SUBIR_CARTA ("SUBIR_CARTA"),
	MODIFICA_ARCHIVOS ("MODIFICA_ARCHIVOS"),
	PUEDE_VER_TAREAS_EN_EJECUCION ("PUEDE_VER_TAREAS_EN_EJECUCION"),
	REASIGNA_TAREA ("REASIGNA_TAREA"),
	PUEDE_VISAR_DOCUMENTO ("PUEDE_VISAR_DOCUMENTO"),
	INGRESA_DATOS_ADICIONALES_AL_SUBIR_ARCHIVO ("INGRESA_DATOS_ADICIONALES_AL_SUBIR_ARCHIVO"),
	PUEDE_FIRMAR_CON_FEA ("PUEDE_FIRMAR_CON_FEA"),
	PUEDE_FIRMAR_CON_APPLET ("PUEDE_FIRMAR_CON_APPLET"),
	PUEDE_BUSCAR ("PUEDE_BUSCAR"),
	PUEDE_VER_DASHBOARD ("PUEDE_VER_DASHBOARD"),
	PUEDE_MANTENER_DATOS ("PUEDE_MANTENER_DATOS"),
	PUEDE_MODIFICAR_DATOS_DE_DOCUMENTO ("PUEDE_MODIFICAR_DATOS_DE_DOCUMENTO"),
	INICIAR_TODOS_LOS_PROCESOS ("INICIAR_TODOS_LOS_PROCESOS"),	
	PUEDE_VER_MANTENEDORES ("PUEDE_VER_MANTENEDORES"),
	PUEDE_CERRAR_EXPEDIENTE ("PUEDE_CERRAR_EXPEDIENTE"),
	AUTO_ASIGNA_PRIMERA_TAREA ("AUTO_ASIGNA_PRIMERA_TAREA"),
	NO_FILTRA_POR_CONFIDENCIALIDAD("NO_FILTRA_POR_CONFIDENCIALIDAD"),
	ADJUNTAR_DOC_EN_TODA_ETAPA("ADJUNTAR_DOC_EN_TODA_ETAPA"),
	PUEDE_MANTENER_NOTIFICIONES_PREDETERMINADAS ("PUEDE_MANTENER_NOTIFICIONES_PREDETERMINADAS"),
	PUEDE_VER_INDICADORES("PUEDE_VER_INDICADORES"),
	PUEDE_MANTENER_LISTA_DISTRIBUCION("PUEDE_MANTENER_LISTA_DISTRIBUCION"),
	PUEDE_MANTENER_PARAMETROS("PUEDE_MANTENER_PARAMETROS"),
	PUEDE_REABRIR_EXPEDIENTE_Y_SATAR_TAREA("PUEDE_REABRIR_EXPEDIENTE_Y_SATAR_TAREA"),
	PUEDE_VINCULAR_EXPEDIENTES("PUEDE_VINCULAR_EXPEDIENTES"),
	PUEDE_DES_VINCULAR_EXPEDIENTES("PUEDE_DES_VINCULAR_EXPEDIENTES"),
	PUEDE_MANTENER_AUTORES("PUEDE_MANTENER_AUTORES"),
	PUEDE_MANTENER_PROCESOS_SOL_CREAC_EXP("PUEDE_MANTENER_PROCESOS_SOL_CREAC_EXP"),
	ENVIO_ARCHIVO_NACIONAL("ENVIO_ARCHIVO_NACIONAL");
	
	private final String nombrePermiso;

	private PermisoType(String nombrePermiso) {
		this.nombrePermiso = nombrePermiso;
	}

	public String getNombrePermiso() {
		return nombrePermiso;
	}
	
}
