
package cl.gob.scj.sgdp.ws.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegistroDocumentoWS", targetNamespace = "http://ws.numdoc.scj.gob.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistroDocumentoWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns cl.gob.scj.sgdp.ws.soap.client.GeneraRegistroDocumentoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generaRegistroDocumento", targetNamespace = "http://ws.numdoc.scj.gob.cl/", className = "cl.gob.scj.sgdp.ws.soap.client.GeneraRegistroDocumento")
    @ResponseWrapper(localName = "generaRegistroDocumentoResponse", targetNamespace = "http://ws.numdoc.scj.gob.cl/", className = "cl.gob.scj.sgdp.ws.soap.client.GeneraRegistroDocumentoResponse2")
    public GeneraRegistroDocumentoResponse generaRegistroDocumento(
        @WebParam(name = "arg0", targetNamespace = "")
        GeneraRegistroDocumentoRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cl.gob.scj.sgdp.ws.soap.client.BorraRegistroDocumentoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borraRegistroDocumento", targetNamespace = "http://ws.numdoc.scj.gob.cl/", className = "cl.gob.scj.sgdp.ws.soap.client.BorraRegistroDocumento")
    @ResponseWrapper(localName = "borraRegistroDocumentoResponse", targetNamespace = "http://ws.numdoc.scj.gob.cl/", className = "cl.gob.scj.sgdp.ws.soap.client.BorraRegistroDocumentoResponse2")
    public BorraRegistroDocumentoResponse borraRegistroDocumento(
        @WebParam(name = "arg0", targetNamespace = "")
        BorraRegistroDocumentoRequest arg0);

}
