
package cl.gob.scj.sgdp.ws.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistroDocumentoWS", targetNamespace = "http://ws.numdoc.scj.gob.cl/", wsdlLocation = "http://172.16.10.77:8080/numeracion-documentos-ws/RegistroDocumentoWS?wsdl")
public class RegistroDocumentoWS_Service
    extends Service
{

    private final static URL REGISTRODOCUMENTOWS_WSDL_LOCATION;
    private final static WebServiceException REGISTRODOCUMENTOWS_EXCEPTION;
    private final static QName REGISTRODOCUMENTOWS_QNAME = new QName("http://ws.numdoc.scj.gob.cl/", "RegistroDocumentoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.10.77:8080/numeracion-documentos-ws/RegistroDocumentoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRODOCUMENTOWS_WSDL_LOCATION = url;
        REGISTRODOCUMENTOWS_EXCEPTION = e;
    }

    public RegistroDocumentoWS_Service() {
        super(__getWsdlLocation(), REGISTRODOCUMENTOWS_QNAME);
    }

    public RegistroDocumentoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRODOCUMENTOWS_QNAME, features);
    }

    public RegistroDocumentoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, REGISTRODOCUMENTOWS_QNAME);
    }

    public RegistroDocumentoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRODOCUMENTOWS_QNAME, features);
    }

    public RegistroDocumentoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistroDocumentoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistroDocumentoWS
     */
    @WebEndpoint(name = "RegistroDocumentoWSPort")
    public RegistroDocumentoWS getRegistroDocumentoWSPort() {
        return super.getPort(new QName("http://ws.numdoc.scj.gob.cl/", "RegistroDocumentoWSPort"), RegistroDocumentoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistroDocumentoWS
     */
    @WebEndpoint(name = "RegistroDocumentoWSPort")
    public RegistroDocumentoWS getRegistroDocumentoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.numdoc.scj.gob.cl/", "RegistroDocumentoWSPort"), RegistroDocumentoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRODOCUMENTOWS_EXCEPTION!= null) {
            throw REGISTRODOCUMENTOWS_EXCEPTION;
        }
        return REGISTRODOCUMENTOWS_WSDL_LOCATION;
    }

}
